let bad=[],good=[],reasons=[];
const $=s=>document.querySelector(s);
const REASONS={"装備集め・ハクスラ":{loot:-1,build:-.8},"移動が多い":{travel_burden:-1,open_world:-.25},"戦闘が単調":{combat:.25,reaction:1,speed:1},"難しすぎる":{difficulty:-1},"ストーリーが弱い":{story:1},"キャラにハマれない":{characters:1},"探索が面倒":{exploration:-.8,travel_burden:-1},"育成・ビルドが合わない":{build:-1,rpg:-.7},"操作感・テンポが合わない":{speed:1,reaction:1},"自由度が低い":{linear:-1,open_world:1}};
const AXIS_WEIGHTS={combat:1.3,parry:1.35,reaction:1.35,story:1.1,characters:1,exploration:.9,open_world:.8,rpg:.7,build:.8,loot:.7,roguelike:.8,speed:1.15,spectacle:.9,linear:.7,travel_burden:1,difficulty:.85};
const realGames=()=>GAMES.filter(g=>!/^ゲーム候補\s*\d+$/.test(g.title));
const gameById=id=>GAMES.find(g=>g.id===id);
function start(){$("#home").classList.add("hide");$("#quiz").classList.remove("hide");renderBad();renderWhy();renderGood();updateCounts()}
function go(n){if(n===2&&!bad.length){alert("まず「つまらなかったゲーム」を1本以上選んでください。");return}document.querySelectorAll(".page").forEach(x=>x.classList.add("hide"));$("#p"+n).classList.remove("hide");$("#bar").style.width=n/3*100+"%";scrollTo({top:0,behavior:"smooth"})}
function list(q,sel,setter,id,type){const box=$(id);box.innerHTML="";const query=(q||"").trim().toLowerCase();if(!query){box.innerHTML='<div class="hint">ゲーム名を入力して検索してください</div>';return}const source=realGames().filter(g=>g.title.toLowerCase().includes(query));source.slice(0,40).forEach(g=>{const b=document.createElement("button"),other=type==="bad"&&good.includes(g.id)||type==="good"&&bad.includes(g.id);b.className="game"+(sel.includes(g.id)?" on":"")+(other?" disabled":"");b.innerHTML=`<span>${g.title}</span>${sel.includes(g.id)?"<b>✓</b>":""}`;b.disabled=other;b.onclick=()=>{if(sel.includes(g.id))setter(sel.filter(x=>x!==g.id));else if(sel.length<5)setter([...sel,g.id]);else alert("最大5本まで選べます。");renderBad();renderGood();updateCounts()};box.appendChild(b)});if(!source.length)box.innerHTML='<div class="hint">見つかりませんでした。別の名前で検索してみてください。</div>'}
function renderBad(){list($("#badSearch").value,bad,x=>bad=x,"#bad","bad");$("#badSel").innerHTML=bad.map(i=>`<span class="pill">${gameById(i).title}<button onclick="removeBad(${i})">×</button></span>`).join("")}
function renderGood(){list($("#goodSearch").value,good,x=>good=x,"#good","good");$("#goodSel").innerHTML=good.map(i=>`<span class="pill">${gameById(i).title}<button onclick="removeGood(${i})">×</button></span>`).join("")}
function removeBad(id){bad=bad.filter(x=>x!==id);renderBad();updateCounts()}
function removeGood(id){good=good.filter(x=>x!==id);renderGood();updateCounts()}
function renderWhy(){const box=$("#reasons");box.innerHTML=Object.keys(REASONS).map(r=>`<button class="reason ${reasons.includes(r)?"on":""}" data-reason="${r}">${r}</button>`).join("");box.querySelectorAll(".reason").forEach(b=>b.onclick=()=>{const r=b.dataset.reason;reasons=reasons.includes(r)?reasons.filter(x=>x!==r):[...reasons,r];b.classList.toggle("on",reasons.includes(r));updateCounts()})}
function updateCounts(){["bad","good"].forEach(t=>$("#"+t+"Count").textContent=`${t==="bad"?bad.length:good.length}/5`);$("#reasonCount").textContent=`${reasons.length}個`}
function distance(a,b){let s=0,w=0;for(const k of AXES){const z=AXIS_WEIGHTS[k]||1;s+=z*Math.abs((a[k]??.5)-(b[k]??.5));w+=z}return s/w}
function reasonFit(p){if(!reasons.length)return .5;let total=0,w=0;for(const r of reasons)for(const[k,d]of Object.entries(REASONS[r])){const v=p[k]??.5;total+=d>0?v*Math.abs(d):(1-v)*Math.abs(d);w+=Math.abs(d)}return total/w}
function explain(g){const p=g.profile,a=[];if(p.combat>=.82)a.push("戦闘の手応え");if(p.reaction>=.78)a.push("反応を求められる操作");if(p.speed>=.8)a.push("テンポの良さ");if(p.story>=.82)a.push("ストーリー重視");if(p.exploration>=.75)a.push("探索の楽しさ");if(p.open_world>=.75)a.push("自由度の高さ");if(p.roguelike>=.7)a.push("繰り返し遊ぶ構造");if(p.travel_burden<=.2)a.push("移動の負担が少ない");return a.slice(0,3).join("・")||"ゲーム全体のバランス"}
function shareData(){return{bad:[...bad],good:[...good],reasons:[...reasons]}}
function buildShareUrl(){const s=shareData(),p=new URLSearchParams();if(s.bad.length)p.set("bad",s.bad.join(","));if(s.good.length)p.set("good",s.good.join(","));if(s.reasons.length)p.set("reason",s.reasons.map(encodeURIComponent).join(","));return location.origin+location.pathname+"?"+p.toString()}
function shareResult(title){const text=`${title}が次にハマるかも？ GAMEFINDERで「つまらなかったゲーム」から診断してみた。`;const url=buildShareUrl();if(navigator.share){navigator.share({title:"GAMEFINDER 診断結果",text,url}).catch(()=>{})}else{navigator.clipboard?.writeText(`${text}\n${url}`);alert("診断結果の共有用URLをコピーしました！")}}
function shareX(title){const text=`${title}が次にハマるかも？\nGAMEFINDERで「つまらなかったゲーム」から診断してみた。\n#GAMEFINDER`;const url=buildShareUrl();window.open("https://twitter.com/intent/tweet?text="+encodeURIComponent(text)+"&url="+encodeURIComponent(url),"_blank","noopener,noreferrer")}
function seriesKey(title){let t=title.toLowerCase().replace(/[：:！!？?・'’“”"()（）\[\]【】]/g,"").replace(/\s+/g," ").trim();t=t.replace(/\b(remastered|remake|definitive edition|directors cut|director's cut|complete edition|gold edition|goty edition|game of the year edition)\b/g,"");const m=t.match(/^(.+?)(?:\s+(?:ii|iii|iv|v|vi|vii|viii|ix|x|xi|xii|xiii|xiv|xv|xvi|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16))?(?:\s*[-–—]\s*.+)?$/);return(m?.[1]||t).trim()}
function diversify(ranked){const out=[],used=new Set();for(const x of ranked){const key=seriesKey(x.g.title);if(used.has(key))continue;out.push(x);used.add(key);if(out.length>=5)break}if(out.length<5){for(const x of ranked){if(out.some(y=>y.g.id===x.g.id))continue;out.push(x);if(out.length>=5)break}}return out}
function loadSharedDiagnosis(){const p=new URLSearchParams(location.search);const parseIds=k=>{const v=p.get(k);if(!v)return[];return v.split(",").map(Number).filter(id=>Number.isInteger(id)&&gameById(id)&&!/^ゲーム候補\s*\d+$/.test(gameById(id).title)).slice(0,5)};const sharedBad=parseIds("bad"),sharedGood=parseIds("good"),sharedReasons=(p.get("reason")||"").split(",").filter(Boolean).map(decodeURIComponent).filter(r=>REASONS[r]);if(!sharedBad.length)return false;bad=sharedBad;good=sharedGood.filter(id=>!bad.includes(id));reasons=[...new Set(sharedReasons)];updateCounts();diagnose();return true}
function diagnose(){if(!bad.length){alert("つまらなかったゲームを1本以上選んでください。");go(1);return}const candidates=realGames().filter(g=>!bad.includes(g.id)&&!good.includes(g.id)),bp=bad.map(i=>gameById(i).profile),gp=good.map(i=>gameById(i).profile);const ranked=candidates.map(g=>{const goodSim=gp.length?1-gp.reduce((s,p)=>s+distance(p,g.profile),0)/gp.length:.5;const badAvoid=bp.length?bp.reduce((s,p)=>s+distance(p,g.profile),0)/bp.length:.5;const fit=reasonFit(g.profile);const score=gp.length&&reasons.length?goodSim*.45+badAvoid*.35+fit*.2:gp.length?goodSim*.62+badAvoid*.38:reasons.length?badAvoid*.7+fit*.3:badAvoid;return{g,score,goodSim,badAvoid}}).sort((a,b)=>b.score-a.score);showResult(diversify(ranked))}
function injectAd(){const box=document.querySelector(".ad-slot");if(!box)return;box.innerHTML="";const label=document.createElement("span");label.textContent="広告";box.appendChild(label);const s=document.createElement("script");s.src="https://adm.shinobi.jp/s/2de0301b90b55526b609ff3bf62fbb1d";s.async=true;box.appendChild(s)}
function showResult(ranked){document.querySelectorAll(".page").forEach(x=>x.classList.add("hide"));$("#result").classList.remove("hide");$("#bar").style.width="100%";const top=ranked[0],confidence=Math.round(Math.min(98,45+bad.length*7+good.length*5+reasons.length*3));$("#result").innerHTML=`<div class="result-head"><small>YOUR RESULT</small><h2>次にハマる可能性が高いゲーム</h2><p class="confidence">入力情報の充実度 <b>${confidence}%</b>　${bad.length}本の「地雷」＋${good.length}本の「好き」＋${reasons.length}個の理由から分析</p></div><div class="hero-result"><div class="rank">#1</div><div class="score">${Math.round(top.score*100)}<small>% MATCH</small></div><h2>${top.g.title}</h2><p>あなたの「好き」に近く、選んだ「地雷」から離れた候補です。</p><div class="match-tags"><span>好きとの相性 ${Math.round(top.goodSim*100)}%</span><span>地雷回避 ${Math.round(top.badAvoid*100)}%</span></div><button class="share-btn" onclick='shareResult(${JSON.stringify(top.g.title)})'>結果をシェアする ↗</button><button class="share-x" onclick='shareX(${JSON.stringify(top.g.title)})'>Xでシェア ↗</button></div><div class="ad-slot" aria-label="広告"></div><h2 class="section-title">おすすめTOP5</h2>${ranked.map((x,i)=>`<article class="card result-card"><div class="rank-mini">0${i+1}</div><div><h3>${x.g.title}</h3><p>合いそうな理由：<b>${explain(x.g)}</b></p><div class="bars"><span>好き ${Math.round(x.goodSim*100)}%</span><span>地雷回避 ${Math.round(x.badAvoid*100)}%</span></div></div></article>`).join("")}<div class="result-note"><b>この診断について</b><p>作品の評価ではなく、ゲームごとの特徴を比較しています。結果は「絶対にハマる」ことを保証するものではなく、あなたの入力から算出した参考情報です。</p></div><button class="restart" onclick="location.href=location.pathname">最初からやり直す</button>`;injectAd()}
loadSharedDiagnosis();