let bad=[],good=[],reasons=[];const $=s=>document.querySelector(s);
const R={"装備集め・ハクスラ":{loot:.35,build:.25},"移動が多い":{travel_burden:.4,open_world:.2},"戦闘が単調":{combat:.3,reaction:.2,speed:.15},"難しすぎる":{difficulty:.4},"ストーリーが弱い":{story:.4},"キャラにハマれない":{characters:.4},"探索が面倒":{exploration:.3,travel_burden:.3},"育成・ビルドが合わない":{build:.35,rpg:.2},"操作感・テンポが合わない":{speed:.3,reaction:.2},"自由度が低い":{linear:.35}};
function start(){$("#home").classList.add("hide");$("#quiz").classList.remove("hide");renderBad();renderGood();renderWhy()}
function go(n){document.querySelectorAll(".page").forEach(x=>x.classList.add("hide"));$("#p"+n).classList.remove("hide");$("#bar").style.width=(n/3*100)+"%";scrollTo(0,0)}
function list(q,sel,setter,id){let box=$(id);box.innerHTML="";GAMES.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())).slice(0,60).forEach(g=>{let b=document.createElement("button");b.className="game"+(sel.includes(g.id)?" on":"");b.textContent=g.title;b.onclick=()=>{if(sel.includes(g.id))setter(sel.filter(x=>x!==g.id));else if(sel.length<5)setter([...sel,g.id]);renderBad();renderGood()};box.appendChild(b)})}
function renderBad(){list($("#badSearch").value,bad,x=>bad=x,"#bad");$("#badSel").innerHTML=bad.map(i=>`<span class="pill">${GAMES.find(g=>g.id===i).title}</span>`).join("")}
function renderGood(){list($("#goodSearch").value,good,x=>good=x,"#good");$("#goodSel").innerHTML=good.map(i=>`<span class="pill">${GAMES.find(g=>g.id===i).title}</span>`).join("")}
function renderWhy(){reasons=[];let box=$("#reasons");box.innerHTML=Object.keys(R).map(x=>`<button onclick="this.classList.toggle('on');this.classList.contains('on')?reasons.push('${x}'):reasons=reasons.filter(v=>v!=='${x}')">${x}</button>`).join("")}
function dist(a,b){let s=0,w=0;for(const k of AXES){let z=["combat","parry","reaction","story","characters"].includes(k)?1.4:1;s+=z*Math.abs(a[k]-b[k]);w+=z}return s/w}
function diagnose(){let bp=bad.map(i=>GAMES.find(g=>g.id===i).profile),gp=good.map(i=>GAMES.find(g=>g.id===i).profile);let ranked=GAMES.filter(g=>!bad.includes(g.id)&&!good.includes(g.id)).map(g=>{let d=gp.length?gp.reduce((s,p)=>s+dist(p,g.profile),0)/gp.length:.5;let avoid=bp.length?bp.reduce((s,p)=>s+dist(p,g.profile),0)/bp.length:.5:0;let penalty=0;for(const r of reasons)for(const[k,v]of Object.entries(R[r]))penalty+=g.profile[k]*v;return{g,score:d*.68+(1-avoid)*.32+penalty*.08}}).sort((a,b)=>a.score-b.score).slice(0,5);let top=ranked[0];document.querySelectorAll(".page").forEach(x=>x.classList.add("hide"));$("#result").classList.remove("hide");$("#bar").style.width="100%";$("#result").innerHTML=`<small>YOUR RESULT</small><h2>あなたに合う可能性が高いゲーム</h2><div class="card"><div class="score">${Math.max(1,Math.min(99,Math.round(99-top.score*70)))}%</div><h2>${top.g.title}</h2><p>好きだったゲームとの距離を近づけ、つまらなかったゲームとの距離を取り、さらに「嫌だった理由」を減点して算出。</p></div><h2>おすすめTOP5</h2>${ranked.map((x,i)=>`<div class="card"><small>0${i+1}</small><h3>${x.g.title}</h3><p>戦闘 ${Math.round(x.g.profile.combat*100)} / 反応 ${Math.round(x.g.profile.reaction*100)} / ストーリー ${Math.round(x.g.profile.story*100)} / 探索 ${Math.round(x.g.profile.exploration*100)}</p></div>`).join("")}<button onclick="location.reload()">もう一度診断</button>`}