/* GAMEFINDER 日本語検索: 正式日本語名・略称・カタカナから英語DBを検索 */
const JP_ALIASES={
  "Elden Ring":["エルデンリング","エルデン","elden"],"Elden Ring Nightreign":["エルデンリング ナイトレイン","ナイトレイン","nightreign"],"Elden Ring Tarnished Edition":["エルデンリング ターニッシュド エディション"],
  "Sekiro: Shadows Die Twice":["隻狼","せきろう","セキロ","sekiro"],"Dark Souls Remastered":["ダークソウル","ダクソ","ダクソ1"],"Dark Souls II: Scholar of the First Sin":["ダークソウル2","ダクソ2"],"Dark Souls III":["ダークソウル3","ダクソ3"],"Demon's Souls":["デモンズソウル","デモンズ"],"Bloodborne":["ブラッドボーン","ブラボ"],"Armored Core VI: Fires of Rubicon":["アーマードコア6","アーマードコアVI","AC6","アーマードコア"],"Lies of P":["Lies of P","ライスオブP","ライズオブP","嘘のP"],"Nioh":["仁王","仁王1"],"Nioh 2":["仁王2"],"Nioh 3":["仁王3"],"Rise of the Ronin":["ライズオブザローニン","ローニン"],"Wo Long: Fallen Dynasty":["ウォーロン","Wo Long"],"Mortal Shell":["モータルシェル"],"Thymesia":["タイメシア"],"Stellar Blade":["ステラブレイド","ステラ"],"Black Myth: Wukong":["黒神話 悟空","黒神話：悟空","悟空"],
  "The Legend of Zelda: Tears of the Kingdom":["ゼルダの伝説 ティアーズ オブ ザ キングダム","ティアキン"],"The Legend of Zelda: Breath of the Wild":["ゼルダの伝説 ブレス オブ ザ ワイルド","ブレワイ"],"Super Mario Odyssey":["スーパーマリオ オデッセイ","マリオオデッセイ"],"Super Mario Bros. Wonder":["スーパーマリオブラザーズ ワンダー","マリオワンダー"],"Mario Kart World":["マリオカート ワールド","マリカワールド"],"Mario Kart 8 Deluxe":["マリオカート8 デラックス","マリカ8"],"Animal Crossing: New Horizons":["あつまれ どうぶつの森","あつ森"],"Super Smash Bros. Ultimate":["大乱闘スマッシュブラザーズ SPECIAL","スマブラSP","スマブラ"],"Pokemon Scarlet":["ポケットモンスター スカーレット","ポケモン スカーレット"],"Pokemon Violet":["ポケットモンスター バイオレット","ポケモン バイオレット"],"Pokemon Legends: Arceus":["Pokémon LEGENDS アルセウス","ポケモン アルセウス","アルセウス"],"Splatoon 3":["スプラトゥーン3","スプラ3"],"Splatoon 2":["スプラトゥーン2","スプラ2"],"Splatoon":["スプラトゥーン","スプラ"],"Metroid Dread":["メトロイド ドレッド","メトロイド"],"Metroid Prime Remastered":["メトロイドプライム リマスタード"],"Kirby and the Forgotten Land":["星のカービィ ディスカバリー","カービィ ディスカバリー"],"Pikmin 4":["ピクミン4","ピクミン"],
  "Final Fantasy VII Rebirth":["ファイナルファンタジーVII リバース","FF7リバース","FF7R"],"Final Fantasy VII Remake":["ファイナルファンタジーVII リメイク","FF7リメイク","FF7R"],"Final Fantasy XVI":["ファイナルファンタジーXVI","FF16","FF16"],"Final Fantasy XV":["ファイナルファンタジーXV","FF15"],"Final Fantasy XIV Online":["ファイナルファンタジーXIV","FF14"],"Dragon Quest XI S":["ドラゴンクエストXI","ドラクエ11","DQ11"],"Dragon Quest III HD-2D Remake":["ドラゴンクエストIII HD-2D版","ドラクエ3","DQ3"],"Kingdom Hearts III":["キングダムハーツ3","KH3"],"NieR: Automata":["ニーア オートマタ","ニーア"],"Persona 5 Royal":["ペルソナ5 ザ・ロイヤル","P5R","ペルソナ5"],"Persona 4 Golden":["ペルソナ4 ザ・ゴールデン","P4G","ペルソナ4"],"Persona 3 Reload":["ペルソナ3 リロード","P3R","ペルソナ3"],"Metaphor: ReFantazio":["メタファー リファンタジオ","メタファー"],"Like a Dragon: Infinite Wealth":["龍が如く8","龍が如く8外伝ではない","如く8"],"Yakuza 0":["龍が如く0","龍が如く0 誓いの場所"],
  "Monster Hunter Wilds":["モンスターハンターワイルズ","モンハンワイルズ","ワイルズ","MHWilds"],"Monster Hunter World":["モンスターハンター ワールド","モンハンワールド","MHW"],"Monster Hunter World: Iceborne":["モンスターハンターワールド アイスボーン","アイスボーン","MHW:I"],"Monster Hunter Rise":["モンスターハンターライズ","モンハンライズ","ライズ"],"Monster Hunter Rise: Sunbreak":["モンスターハンターライズ サンブレイク","サンブレイク"],"Devil May Cry 5":["デビル メイ クライ5","DMC5","デビルメイクライ5"],"Resident Evil 4 Remake":["バイオハザード RE:4","バイオ4リメイク","RE4"],"Resident Evil 7":["バイオハザード7","バイオ7"],"Resident Evil Village":["バイオハザード ヴィレッジ","バイオ8","RE8"],"Dragon's Dogma 2":["ドラゴンズドグマ2","ドグマ2","DD2"],"Onimusha: Way of the Sword":["鬼武者 Way of the Sword","鬼武者 ワールド オブ ザ ソード","鬼武者 新作","鬼武者"],"Onimusha: Warlords":["鬼武者","鬼武者1"],"Kunitsu-Gami: Path of the Goddess":["祇","祇：Path of the Goddess","くにつがみ"],
  "Hades 2":["Hades II","ハデス2","ハデスⅡ","ハデス"],"Returnal":["リターナル"],"Hollow Knight":["ホロウナイト"],"Ghostrunner":["ゴーストランナー"],"Ghostrunner 2":["ゴーストランナー2"],"Sifu":["師父","シフ"],"God of War Ragnarök":["ゴッド・オブ・ウォー ラグナロク","GOWラグナロク"],"God of War 2018":["ゴッド・オブ・ウォー","GOW"],"Ghost of Tsushima Director's Cut":["ゴースト・オブ・ツシマ","ツシマ"],"Marvel's Spider-Man 2":["Marvel's Spider-Man 2","スパイダーマン2"],"Astro Bot":["アストロボット"],"The Witcher 3: Wild Hunt":["ウィッチャー3"],"Cyberpunk 2077":["サイバーパンク2077","サイパン"],"Baldur's Gate 3":["バルダーズ・ゲート3","BG3"],"Starfield":["スターフィールド"],"Hogwarts Legacy":["ホグワーツ レガシー","ホグワーツ"],"Grand Theft Auto V":["グランド・セフト・オートV","GTA5","GTA V"],"Red Dead Redemption 2":["レッド・デッド・リデンプション2","RDR2"],"Assassin's Creed Shadows":["アサシン クリード シャドウズ","アサクリ シャドウズ"],"Prince of Persia: The Lost Crown":["プリンス オブ ペルシャ 失われた王冠"],
  "Yo-kai Watch 4":["妖怪ウォッチ4","妖怪ウォッチ4++","妖怪ウォッチ"],"Yo-kai Watch 3":["妖怪ウォッチ3"],"Yo-kai Watch 2":["妖怪ウォッチ2"],"Yo-kai Watch 1":["妖怪ウォッチ","妖怪ウォッチ1"],"Fate/Samurai Remnant":["Fate/Samurai Remnant","フェイト サムライレムナント","サムレム"],"Granblue Fantasy: Relink":["グランブルーファンタジー リリンク","グラブルリリンク","リリンク"],"The Hundred Line: Last Defense Academy":["The Hundred Line","ハンドレッドライン","ハンドレッドライン 最終防衛学園"]
};
const normJP=s=>String(s||"").toLowerCase().replace(/[\s　:：・'’\-‐‑–—]/g,"");
const jpSearchText=g=>[g.title,...(JP_ALIASES[g.title]||[])].map(normJP).join(" ");
function list(q,sel,setter,id,type){const box=$(id);box.innerHTML="";const query=normJP(q);if(!query){box.innerHTML='<div class="hint">ゲーム名を入力して検索してください（日本語・英語・略称OK）</div>';return}const source=realGames().filter(g=>jpSearchText(g).includes(query));source.slice(0,40).forEach(g=>{const b=document.createElement("button"),other=type==="bad"&&good.includes(g.id)||type==="good"&&bad.includes(g.id);b.className="game"+(sel.includes(g.id)?" on":"")+(other?" disabled":"");const alias=(JP_ALIASES[g.title]||[])[0];b.innerHTML=`<span>${alias||g.title}${alias&&alias!==g.title?`<small class="alias-en">${g.title}</small>`:""}</span>${sel.includes(g.id)?"<b>✓</b>":""}`;b.disabled=other;b.onclick=()=>{if(sel.includes(g.id))setter(sel.filter(x=>x!==g.id));else if(sel.length<5)setter([...sel,g.id]);else alert("最大5本まで選べます。");renderBad();renderGood();updateCounts()};box.appendChild(b)});if(!source.length)box.innerHTML='<div class="hint">見つかりませんでした。日本語名・英語名・略称を変えて試してください。</div>'}
